<?php
require_once __DIR__ . '/includes/site-data.php';
$items = tt_blog_posts();
$items = $items ?: [
    ['icon' => 'fa-newspaper', 'title' => 'How to Choose an IT Course', 'short_desc' => 'Pick a practical track based on your career goal.', 'description' => 'Compare your interest, current skill level, project goals and placement timeline before choosing a course.', 'image' => 'assets/images/home1.webp'],
    ['icon' => 'fa-code', 'title' => 'Why Projects Matter', 'short_desc' => 'Portfolio projects help prove your skills in interviews.', 'description' => 'Live projects show practical problem solving, coding confidence and the ability to explain your work.', 'image' => 'uploads/media/full-stack-development-20260703-133158-761383.png'],
    ['icon' => 'fa-lightbulb', 'title' => 'Learning from Basics', 'short_desc' => 'A strong foundation makes advanced tools easier.', 'description' => 'Start with fundamentals, practice consistently, then move into tools, frameworks and real-time tasks.', 'image' => 'uploads/media/programming-languages-20260703-133210-630417.png'],
];
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><?php tt_render_seo(['title'=>'Blog | Talentteno Institute','description'=>'Talentteno blog posts and IT learning guidance.','canonical'=>tt_abs_url('blog.php')]); ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Space+Grotesk:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><link rel="stylesheet" href="assets/css/site-pages.css?v=20260717-navsize1"></head>
<body class="static-site blog-page"><div class="site-shell"><header class="site-header"><div class="site-container nav-wrap"><a class="brand" href="index.php"><span class="brand-mark logo-mark"><img src="assets/images/logot-transparent.png" alt="Talentteno Institute logo" width="132" height="62" decoding="async" fetchpriority="high"></span><span><span class="brand-name">Talentteno Institute</span><span class="brand-sub">IT TRAINING INSTITUTE</span></span></a><nav class="site-nav">
                <a href="index.php">Home</a>
                <a href="about.php">About</a>
                <div class="nav-item has-menu"><a href="course.php">Course <i class="fa-solid fa-chevron-down"></i></a><div class="nav-menu"><a href="shorttermcourse.php">Short Term Course</a><a href="popularcourse.php">Popular Course</a><a href="advancecourse.php">Advance Course</a></div></div>
                <a href="gallery.php">Gallery</a>
                <a href="contact.php">Contact</a>
                <div class="nav-item has-menu more-menu"><a href="#">More <i class="fa-solid fa-chevron-down"></i></a><div class="nav-menu"><a href="services.php">Services</a><a href="career.php">Career</a><a href="blog.php">Blog</a><a href="project.php">Project</a></div></div>
            </nav><button class="menu-button" type="button" aria-label="Open menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div></header><main class="page-main"><section class="page-hero has-page-hero-image"><img class="page-hero-bg" src="assets/images/blog.png" alt="" aria-hidden="true" decoding="async" fetchpriority="high"><span class="page-hero-overlay" aria-hidden="true"></span><div class="site-container reveal"><span class="hero-kicker"><i class="fa-solid fa-newspaper"></i> Learning Notes</span><h1>Blog</h1><p>Insights, learning tips and practical guidance for students preparing for IT careers.</p></div></section><section class="section"><div class="site-container detail-grid rich-detail-grid"><?php foreach ($items as $item): ?><?php $image = tt_item_image($item, 'blog'); ?><article class="detail-tile rich-detail-card reveal"><div class="rich-detail-image"><img src="<?= tt_h($image) ?>" alt="<?= tt_h($item['title'] ?? 'Talentteno blog') ?>" loading="lazy" decoding="async"></div><div class="rich-detail-body"><i class="fa-solid <?= tt_h($item['icon'] ?? 'fa-newspaper') ?>"></i><h3><?= tt_h($item['title']) ?></h3><p class="rich-detail-short"><?= tt_h(($item['short_desc'] ?? '') ?: ($item['description'] ?? '')) ?></p><?php if (!empty($item['description']) && ($item['description'] !== ($item['short_desc'] ?? ''))): ?><p class="rich-detail-more"><?= tt_h($item['description']) ?></p><?php endif; ?><a class="rich-detail-link" href="contact.php?topic=<?= rawurlencode($item['title'] ?? 'blog') ?>">More Details <i class="fa-solid fa-arrow-right"></i></a></div></article><?php endforeach; ?></div></section></main><?php include __DIR__ . '/includes/footer.php'; ?></div><script src="assets/js/site-pages.js?v=20260716-whatsapp1" defer></script></body></html>
