<?php
require_once __DIR__ . '/includes/site-data.php';
$items = tt_projects();
$items = $items ?: [
    ['icon' => 'fa-diagram-project', 'title' => 'Live Website Project', 'short_desc' => 'Build a complete responsive business website.', 'description' => 'Plan pages, create responsive sections, connect enquiry forms and publish portfolio-ready work.', 'image' => 'uploads/media/full-stack-development-20260703-133158-761383.png'],
    ['icon' => 'fa-database', 'title' => 'Data Dashboard Project', 'short_desc' => 'Practice data cleaning, reporting and visualization.', 'description' => 'Use real datasets to clean data, prepare charts and explain business insights clearly.', 'image' => 'uploads/media/data-analyst-20260703-133130-702998.png'],
    ['icon' => 'fa-shield-halved', 'title' => 'Cyber Lab Project', 'short_desc' => 'Learn practical security workflows in guided labs.', 'description' => 'Practice security basics, scanning workflow, reporting and safe lab documentation.', 'image' => 'uploads/media/cyber-security-20260703-133329-242125.png'],
];
?>
<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><?php tt_render_seo(['title'=>'Projects | Talentteno Institute','description'=>'Student projects and practical training work at Talentteno Institute.','canonical'=>tt_abs_url('project.php')]); ?><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800&family=Space+Grotesk:wght@600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><link rel="stylesheet" href="assets/css/site-pages.min.css?v=20260718-footerhover1"></head>
<body class="static-site project-page"><div class="site-shell"><header class="site-header"><div class="site-container nav-wrap"><a class="brand" href="index.php"><span class="brand-mark logo-mark"><img src="uploads/optimized/logot-transparent-w64.webp" srcset="uploads/optimized/logot-transparent-w64.webp 64w, uploads/optimized/logot-transparent-w128.webp 128w" sizes="(max-width: 980px) 58px, 68px" alt="Talentteno Institute logo" width="68" height="68" decoding="async"></span><span><span class="brand-name">Talentteno Institute</span><span class="brand-sub">IT TRAINING INSTITUTE</span></span></a><nav class="site-nav">
                <a href="index.php">Home</a>
                <a href="about.php">About</a>
                <div class="nav-item has-menu"><a href="course.php">Course <i class="fa-solid fa-chevron-down"></i></a><div class="nav-menu"><a href="shorttermcourse.php">Short Term Course</a><a href="popularcourse.php">Popular Course</a><a href="advancecourse.php">Advance Course</a></div></div>
                <a href="gallery.php">Gallery</a>
                <a href="contact.php">Contact</a>
                <div class="nav-item has-menu more-menu"><a href="#">More <i class="fa-solid fa-chevron-down"></i></a><div class="nav-menu"><a href="services.php">Services</a><a href="career.php">Career</a><a href="blog.php">Blog</a><a href="project.php">Project</a></div></div>
            </nav><button class="menu-button" type="button" aria-label="Open menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div></header><main class="page-main"><section class="page-hero has-page-hero-image"><img class="page-hero-bg" src="assets/images/project.png" alt="" aria-hidden="true" decoding="async" fetchpriority="high"><span class="page-hero-overlay" aria-hidden="true"></span><div class="site-container reveal"><span class="hero-kicker"><i class="fa-solid fa-diagram-project"></i> Practical Work</span><h1>Projects</h1><p>Explore practical project work that helps students build portfolio-ready technical confidence.</p></div></section><section class="section"><div class="site-container detail-grid rich-detail-grid"><?php foreach ($items as $item): ?><?php $image = tt_item_image($item, 'project'); ?><article class="detail-tile rich-detail-card reveal"><div class="rich-detail-image"><img src="<?= tt_h($image) ?>" alt="<?= tt_h($item['title'] ?? 'Talentteno project') ?>" loading="lazy" decoding="async"></div><div class="rich-detail-body"><i class="fa-solid <?= tt_h($item['icon'] ?? 'fa-diagram-project') ?>"></i><h3><?= tt_h($item['title']) ?></h3><p class="rich-detail-short"><?= tt_h(($item['short_desc'] ?? '') ?: ($item['description'] ?? '')) ?></p><?php if (!empty($item['description']) && ($item['description'] !== ($item['short_desc'] ?? ''))): ?><p class="rich-detail-more"><?= tt_h($item['description']) ?></p><?php endif; ?><button type="button" class="rich-detail-link" data-smd-trigger data-smd-title="<?= tt_h($item['title'] ?? '') ?>" data-smd-category="Project" data-smd-description="<?= tt_h(($item['description'] ?? '') ?: ($item['short_desc'] ?? '')) ?>" data-smd-image="<?= tt_h($image) ?>" data-smd-features="<?= tt_h(($item['short_desc'] ?? '') . ((!empty($item['description']) && $item['description'] !== ($item['short_desc'] ?? '')) ? "\n" . $item['description'] : '')) ?>" data-smd-enquire="contact.php?topic=<?= rawurlencode($item['title'] ?? 'project') ?>">More Details <i class="fa-solid fa-arrow-right"></i></button></div></article><?php endforeach; ?></div></section></main><?php include __DIR__ . '/includes/footer.php'; ?></div><script src="assets/js/site-pages.min.js?v=20260718-scrollsmooth1" defer></script></body></html>
