CREATE TABLE IF NOT EXISTS brochure_otp_verifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    mobile VARCHAR(10) NOT NULL,
    course_title VARCHAR(150) NOT NULL,
    otp_hash VARCHAR(255) NOT NULL,
    verification_ref_hash VARCHAR(255) NULL,
    expires_at DATETIME NOT NULL,
    resend_available_at DATETIME NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    send_count INT NOT NULL DEFAULT 1,
    verified_at DATETIME NULL,
    used_at DATETIME NULL,
    ip_address VARCHAR(64) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_bov_mobile (mobile),
    INDEX idx_bov_ip_created (ip_address, created_at),
    INDEX idx_bov_ref (verification_ref_hash)
);

CREATE TABLE IF NOT EXISTS brochure_download_leads (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    course_id INT NULL,
    course_title VARCHAR(150) NOT NULL,
    full_name VARCHAR(50) NOT NULL,
    email VARCHAR(190) NOT NULL,
    mobile VARCHAR(10) NOT NULL,
    degree VARCHAR(100) NOT NULL,
    college VARCHAR(150) NOT NULL,
    address VARCHAR(300) NOT NULL,
    current_status VARCHAR(30) NOT NULL,
    mobile_verified TINYINT(1) NOT NULL DEFAULT 0,
    otp_verification_id BIGINT UNSIGNED NOT NULL,
    captcha_verified TINYINT(1) NOT NULL DEFAULT 0,
    ip_address VARCHAR(64) NULL,
    user_agent VARCHAR(255) NULL,
    download_token_hash VARCHAR(255) NOT NULL,
    token_expires_at DATETIME NOT NULL,
    downloaded_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_bdl_mobile (mobile),
    INDEX idx_bdl_email (email),
    INDEX idx_bdl_course_title (course_title),
    INDEX idx_bdl_created_at (created_at),
    INDEX idx_bdl_download_token_hash (download_token_hash)
);
