-- =============================================
-- Talentteno Institute — Weekly Offers Table
-- Migration: run once, safe to re-run
-- =============================================

CREATE TABLE IF NOT EXISTS offers (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    course_id           INT DEFAULT NULL,
    title               VARCHAR(255) NOT NULL,
    slug                VARCHAR(255) NOT NULL,
    course_name         VARCHAR(255) NOT NULL DEFAULT '',
    category            VARCHAR(100) NOT NULL DEFAULT '',
    badge_text          VARCHAR(100) NOT NULL DEFAULT 'This Week Only',
    short_description   VARCHAR(500) NOT NULL DEFAULT '',
    full_description    TEXT,
    poster_image        VARCHAR(255) NOT NULL DEFAULT '',
    poster_alt          VARCHAR(255) NOT NULL DEFAULT '',
    hero_image          VARCHAR(255) NOT NULL DEFAULT '',
    hero_alt            VARCHAR(255) NOT NULL DEFAULT '',
    original_fee        DECIMAL(10,2) DEFAULT 0,
    offer_fee           DECIMAL(10,2) DEFAULT 0,
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    currency            VARCHAR(10) NOT NULL DEFAULT 'INR',
    emi_available       TINYINT(1) NOT NULL DEFAULT 0,
    emi_description     VARCHAR(255) NOT NULL DEFAULT '',
    start_date          DATE DEFAULT NULL,
    end_date            DATE DEFAULT NULL,
    registration_end_date DATE DEFAULT NULL,
    available_seats     INT DEFAULT NULL,
    seats_filled        INT NOT NULL DEFAULT 0,
    show_remaining_seats TINYINT(1) NOT NULL DEFAULT 1,
    course_duration     VARCHAR(100) NOT NULL DEFAULT '',
    training_mode       ENUM('Offline','Online','Hybrid') NOT NULL DEFAULT 'Offline',
    batch_timing        VARCHAR(150) NOT NULL DEFAULT '',
    course_level        ENUM('Beginner','Intermediate','Advanced') NOT NULL DEFAULT 'Beginner',
    certificate_available   TINYINT(1) NOT NULL DEFAULT 1,
    internship_available    TINYINT(1) NOT NULL DEFAULT 0,
    placement_available     TINYINT(1) NOT NULL DEFAULT 0,
    highlights          TEXT,
    learning_outcomes   TEXT,
    eligibility         TEXT,
    career_opportunities TEXT,
    terms_conditions    TEXT,
    cta_label           VARCHAR(100) NOT NULL DEFAULT 'Reserve Your Seat',
    cta_url             VARCHAR(255) NOT NULL DEFAULT 'contact.php',
    is_featured         TINYINT(1) NOT NULL DEFAULT 0,
    show_on_offers_page TINYINT(1) NOT NULL DEFAULT 1,
    show_on_home_page   TINYINT(1) NOT NULL DEFAULT 0,
    status              ENUM('draft','active','inactive') NOT NULL DEFAULT 'draft',
    display_order       INT NOT NULL DEFAULT 0,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    INDEX idx_status        (status),
    INDEX idx_featured      (is_featured),
    INDEX idx_start_date    (start_date),
    INDEX idx_end_date      (end_date),
    INDEX idx_display_order (display_order),
    INDEX idx_course_id     (course_id),
    UNIQUE KEY uq_slug      (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
